export const ADD_PRODUCT_REQUEST = "ADD_PRODUCT_REQUEST";
export const ADD_PRODUCT_SUCCESS = "ADD_PRODUCT_SUCCESS";
export const ADD_PRODUCT_FAILED = "ADD_PRODUCT_FAILED";

export const SHOW_PRODUCT_REQUEST = "SHOW_PRODUCT_REQUEST";
export const SHOW_PRODUCT_SUCCESS = "SHOW_PRODUCT_SUCCESS";
export const SHOW_PRODUCT_ERR = "SHOW_PRODUCT_ERR";

export const DELETE_PRODUCT_REQUEST = "DELETE_PRODUCT_REQUEST";
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";
export const DELETE_PRODUCT_ERR = "DELETE_PRODUCT_ERR";

export const ADD_ONE_PRODUCT = "ADD_ONE_PRODUCT";

export const EDIT_PRODUCT_REQUEST = "EDIT_PRODUCT_REQUEST";
export const EDIT_PRODUCT_SUCCESS = "EDIT_PRODUCT_SUCCESS";
export const EDIT_PRODUCT_ERROR = "EDIT_PRODUCT_ERROR";

export const EDIT_PRODUCT_TAKE_REQUEST = "EDIT_PRODUCT_TAKE_REQUEST";
export const EDIT_PRODUCT_TAKE_SUCCESS = "EDIT_PRODUCT_TAKE_SUCESS";
export const EDIT_PRODUCT_TAKE_ERR = "EDIT_PRODUCT_TAKE_ERR";

export const PURCHASE_STOCK_REQUEST = "PARCHASE_STOCK_REQUEST";
export const PURCHASE_STOCK_SUCCESS = "PARCHASE_STOCK_SUCCESS";
export const PURCHASE_STOCK_ERR = "PARCHASE_STOCK_ERR";

export const INC_PURCHASE_VALUE_REQUEST = "INC_PURCHASE_VALUE_REQUEST";
export const INC_PURCHASE_VALUE_SUCCESS = "INC_PURCHASE_VALUE_SUCCESS";
export const INC_PURCHASE_VALUE_ERR = "INC_PURCHASE_VALUE_ERR";

export const DOWNLOAD_BAR_CODE_REQUEST = "DOWNLOAD_BAR_CODE_REQUEST";
export const DOWNLOAD_BAR_CODE_SUCCESS = "DOWNLOAD_BAR_CODE_SUCCESS";
export const DOWNLOAD_BAR_CODE_ERR = "DOWNLOAD_BAR_CODE_ERR";

export const BILLING_VALUE_REQUEST = "BILLING_VALUE_REQUEST";
export const BILLING_VALUE_SUCCESS = "BILLING_VALUE_SUCCESS";
export const BILLING_VALUE_ERR = "BILLING_VALUE_ERR";

export const INCREAS_BILLING_QTY_REQUEST = "INCREAS_BILLING_QTY_REQUEST";
export const INCREAS_BILLING_QTY_SUCCESS = "INCREAS_BILLING_QTY_SUCCESS";
export const INCREAS_BILLING_QTY_ERR = "INCREAS_BILLING_QTY_ERR";

export const DECREAS_BILLING_QTY_REQUEST = "DECREAS_BILLING_QTY_REQUEST";
export const DECREAS_BILLING_QTY_SUCCESS = "DECREAS_BILLING_QTY_SUCCESS";
export const DECREAS_BILLING_QTY_ERR = "DECREAS_BILLING_QTY_ERR";

export const DELETE_BILLING_PRO_REQUEST = "DELETE_BILLING_PRO_REQUEST";
export const DELETE_BILLING_PRO_SUCCESS = "DELETE_BILLING_PRO_SUCCESS";
export const DELETE_BILLING_PRO_ERR = "DELETE_BILLING_PRO_ERR";
