export const ADD_PRODUCT_REQUEST = "ADD_PRODUCT_REQUEST";
export const ADD_PRODUCT_SUCCESS = "ADD_PRODUCT_SUCCESS";
export const ADD_PRODUCT_FAILED = "ADD_PRODUCT_FAILED";

export const SHOW_PRODUCT_REQUEST = "SHOW_PRODUCT_REQUEST";
export const SHOW_PRODUCT_SUCCESS = "SHOW_PRODUCT_SUCCESS";
export const SHOW_PRODUCT_ERR = "SHOW_PRODUCT_ERR";

export const DELETE_PRODUCT_REQUEST = "DELETE_PRODUCT_REQUEST";
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";
export const DELETE_PRODUCT_ERR = "DELETE_PRODUCT_ERR";

export const ADD_ONE_PRODUCT = "ADD_ONE_PRODUCT";

export const EDIT_PRODUCT_REQUEST = "EDIT_PRODUCT_REQUEST";
export const EDIT_PRODUCT_SUCCESS = "EDIT_PRODUCT_SUCCESS";
export const EDIT_PRODUCT_ERROR = "EDIT_PRODUCT_ERROR";

export const EDIT_PRODUCT_TAKE_REQUEST = "EDIT_PRODUCT_TAKE_REQUEST";
export const EDIT_PRODUCT_TAKE_SUCCESS = "EDIT_PRODUCT_TAKE_SUCESS";
export const EDIT_PRODUCT_TAKE_ERR = "EDIT_PRODUCT_TAKE_ERR";

export const PURCHASE_STOCK_REQUEST = "PARCHASE_STOCK_REQUEST";
export const PURCHASE_STOCK_SUCCESS = "PARCHASE_STOCK_SUCCESS";
export const PURCHASE_STOCK_ERR = "PARCHASE_STOCK_ERR";

export const INC_PURCHASE_VALUE_REQUEST = "INC_PURCHASE_VALUE_REQUEST";
export const INC_PURCHASE_VALUE_SUCCESS = "INC_PURCHASE_VALUE_SUCCESS";
export const INC_PURCHASE_VALUE_ERR = "INC_PURCHASE_VALUE_ERR";

export const DOWNLOAD_BAR_CODE_REQUEST = "DOWNLOAD_BAR_CODE_REQUEST";
export const DOWNLOAD_BAR_CODE_SUCCESS = "DOWNLOAD_BAR_CODE_SUCCESS";
export const DOWNLOAD_BAR_CODE_ERR = "DOWNLOAD_BAR_CODE_ERR";

export const BILLING_VALUE_REQUEST = "BILLING_VALUE_REQUEST";
export const BILLING_VALUE_SUCCESS = "BILLING_VALUE_SUCCESS";
export const BILLING_VALUE_ERR = "BILLING_VALUE_ERR";

export const INCREAS_BILLING_QTY_REQUEST = "INCREAS_BILLING_QTY_REQUEST";
export const INCREAS_BILLING_QTY_SUCCESS = "INCREAS_BILLING_QTY_SUCCESS";
export const INCREAS_BILLING_QTY_ERR = "INCREAS_BILLING_QTY_ERR";

export const DECREAS_BILLING_QTY_REQUEST = "DECREAS_BILLING_QTY_REQUEST";
export const DECREAS_BILLING_QTY_SUCCESS = "DECREAS_BILLING_QTY_SUCCESS";
export const DECREAS_BILLING_QTY_ERR = "DECREAS_BILLING_QTY_ERR";

export const DELETE_BILLING_PRO_REQUEST = "DELETE_BILLING_PRO_REQUEST";
export const DELETE_BILLING_PRO_SUCCESS = "DELETE_BILLING_PRO_SUCCESS";
export const DELETE_BILLING_PRO_ERR = "DELETE_BILLING_PRO_ERR";

export const LADGER_BOOK_REQUEST = "LADGER_BOOK_REQUEST";
export const LADGER_BOOK_SUCCESS = "LADGER_BOOK_SUCCESS";
export const LADGER_BOOK_ERR = "LADGER_BOOK_ERR";

export const ADD_LADGER_BOOK_REQUEST = "ADD_LADGER_BOOK_REQUEST";
export const ADD_LADGER_BOOK_SUCCESS = "ADD_LADGER_BOOK_SUCCESS";
export const ADD_LADGER_BOOK_ERR = "ADD_LADGER_BOOK_ERR";

export const ADD_CATEGORY_SET_REQUEST = "ADD_CATEGORY_SET_REQUEST";
export const ADD_CATEGORY_SET_SUCCESS = "ADD_CATEGORY_SET_SUCCESS";
export const ADD_CATEGORY_SET_ERR = "ADD_CATEGORY_SET_ERR";

export const SHOW_CATEGORY_SET_REQUEST = "SHOW_CATEGORY_SET_REQUEST";
export const SHOW_CATEGORY_SET_SUCCESS = "SHOW_CATEGORY_SET_SUCCESS";
export const SHOW_CATEGORY_SET_ERR = "SHOW_CATEGORY_SET_ERR";

export const CATEGORY_SET_REQUEST = "CATEGORY_SET_REQUEST";
export const CATEGORY_SET_SUCCESS = "CATEGORY_SET_SUCCESS";
export const CATEGORY_SET_ERR = "CATEGORY_SET_ERR";

export const CATEGORY_DELETE_REQUEST = "CATEGORY_DELETE_REQUEST";
export const CATEGORY_DELETE_SUCCESS = "CATEGORY_DELETE_SUCCESS";
export const CATEGORY_DELETE_ERR = "CATEGORY_DELETE_ERR";

export const CATEGORY_GET_REQUEST = "CATEGORY_GET_REQUEST";
export const CATEGORY_GET_SUCCESS = "CATEGORY_GET_SUCCESS";
export const CATEGORY_GET_ERR = "CATEGORY_GET_ERR";

export const SUB_CATEGORY_REQUEST = "SUB_CATEGORY_REQUEST";
export const SUB_CATEGORY_SUCCESS = "SUB_CATEGORY_SUCCESS";
export const SUB_CATEGORY_ERR = "SUB_CATEGORY_ERR";

export const GET_SUB_CATEGORY_REQUEST = "GET_SUB_CATEGORY_REQUEST";
export const GET_SUB_CATEGORY_SUCCESS = "GET_SUB_CATEGORY_SUCCESS";
export const GET_SUB_CATEGORY_ERR = "GET_SUB_CATEGORY_ERR";

export const DELETE_SUB_CATEGORY_REQUEST = "DELETE_SUB_CATEGORY_REQUEST";
export const DELETE_SUB_CATEGORY_SUCCESS = "DELETE_SUB_CATEGORY_SUCCESS";
export const DELETE_SUB_CATEGORY_ERR = "DELETE_SUB_CATEGORY_ERR";

export const DELETE_LEDGER_REQUEST = "DELETE_LEDGER_REQUEST";
export const DELETE_LEDGER_SUCCESS = "DELETE_LEDGER_SUCCESS";
export const DELETE_LEDGER_ERR = "DELETE_LEDGER_ERR";
