export const PRODUCT_MANAGE_COLUMNS_HIDE_REQUEST =
  "PRODUCT_MANAGE_COLUMNS_HIDE_REQUEST";
export const PRODUCT_MANAGE_COLUMNS_HIDE_SUCCESS =
  "PRODUCT_MANAGE_COLUMNS_HIDE_SUCCESS";
export const PRODUCT_MANAGE_COLUMNS_HIDE_ERR =
  "PRODUCT_MANAGE_COLUMNS_HIDE_ERR";

export const PRODUCT_MANAGE_COLUMNS_HIDE_SHOW_REQUEST =
  "PRODUCT_MANAGE_COLUMNS_HIDE_SHOW_REQUEST";
export const PRODUCT_MANAGE_COLUMNS_HIDE_SHOW_SUCCESS =
  "PRODUCT_MANAGE_COLUMNS_HIDE_SHOW_SUCCESS";
export const PRODUCT_MANAGE_COLUMNS_HIDE_SHOW_ERR =
  "PRODUCT_MANAGE_COLUMNS_HIDE_SHOW_ERR";
