// for Register
export const STAFF_REGISTER_REQUEST = "STAFF_REGISTER_REQUEST";
export const STAFF_REGISTER_FAILED = "STAFF_REGISTER_FAILED";
export const STAFF_LOGOUT = "STAFF_LOGOUT";
export const STAFF_REGISTER_SUCCESS = "STAFF_REGISTER_SUCCESS";

//for Login
export const STAFF_LOGIN_REQUEST = "STAFF_LOGIN_REQUEST";
export const STAFF_LOGIN_SUCCESS = "STAFF_LOGIN_SUCCESS";
export const STAFF_LOGIN_ERROR = "STAFF_LOGIN_ERROR";
export const STAFF_LOGIN_RESET = "STAFF_LOGIN_RESET";

//FOR SHOWING STAFFS
export const STAFF_SHOWING_REQUEST = "STAFF_SHOWING_REQUEST";
export const STAFF_SHOWING_SUCCESS = "STAFF_SHOWING_SUCCESS";
export const STAFF_SHOWING_ERR = "STAFF_SHOWING_ERR";

//For Staffs status Change

export const STAFF_STATUS_REQUEST = "STAFF_STATUS_REQUEST";
export const STAFF_STATUS_SUCCESS = "STAFF_STATUS_SUCCESS";
export const STAFF_STATUS_ERR = "STAFF_STATUS_ERR";
